services:
  app:
    build:
      context: ./webserver/frontend
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: my-laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./webserver/frontend/:/var/www
      - ./webserver/frontend/.env:/var/www/.env
    environment:
      - APP_ENV=local
      - APP_KEY=base64:hmOQxIhSTPmclPKlyI+dRrmVDs+o8wuyESapA7vZgSQ=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_pass
    networks:
      - app-network
    depends_on:
      - db
      - mqtt
    deploy:
      resources:
        limits:
          memory: 512M    # Set the maximum memory usage to 512MB
        reservations:
          memory: 256M    # Set the soft memory reservation to 256MB

  nginx:
    image: nginx:alpine
    container_name: my-nginx
    ports:
      - "8000:80"
    volumes:
      - ./webserver/frontend/:/var/www
      - ./webserver/frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network        
    deploy:
      resources:
        limits:
          memory: 256M    # Set the maximum memory usage to 512MB
        reservations:
          memory: 128M    # Set the soft memory reservation to 256MB

  node:
    platform: linux/arm64/v8 #this line is optional if you are using Mac Silicon chip (M1/M2/M3)
    build:
      context: ./webserver/frontend
      dockerfile: Dockerfile.node
    image: my-laravel-node
    container_name: my-laravel-node
    ports:
    - "3000:3000"
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./webserver/frontend/:/var/www
      - /var/www/node_modules
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M    # Set the maximum memory usage to 512MB
        reservations:
          memory: 256M    # Set the soft memory reservation to 256MB

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: local_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 1G    # Set the maximum memory usage to 512MB
        reservations:
          memory: 512M    # Set the soft memory reservation to 256MB

  # Python Backend (Adjust path if needed)
  python-backend:
    build:
      context: ./ros_box/src/box_generator/src
      dockerfile: Dockerfile
    container_name: local_python_backend
    restart: always
    environment:
      - MQTT_BROKER=mqtt
    depends_on:
      - mqtt
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M    # Set the maximum memory usage to 512MB
        reservations:
          memory: 256m    # Set the soft memory reservation to 256MB

  # Mosquitto MQTT Broker
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: local_mosquitto
    restart: always
    ports:
      - "1883:1883"  # MQTT communication port
      - "9001:9001"  # WebSocket port for MQTT
      - "8883:8883"  # WebSocket port for MQTT
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 256M    # Set the maximum memory usage to 512MB
        reservations:
          memory: 128M    # Set the soft memory reservation to 256MB

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
