// Generated by gencpp from file box_generator/DeleteBox.msg
// DO NOT EDIT!


#ifndef BOX_GENERATOR_MESSAGE_DELETEBOX_H
#define BOX_GENERATOR_MESSAGE_DELETEBOX_H

#include <ros/service_traits.h>


#include <box_generator/DeleteBoxRequest.h>
#include <box_generator/DeleteBoxResponse.h>


namespace box_generator
{

struct DeleteBox
{

typedef DeleteBoxRequest Request;
typedef DeleteBoxResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DeleteBox
} // namespace box_generator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::box_generator::DeleteBox > {
  static const char* value()
  {
    return "82214afe4ff077ebd4b8aa0c572e1255";
  }

  static const char* value(const ::box_generator::DeleteBox&) { return value(); }
};

template<>
struct DataType< ::box_generator::DeleteBox > {
  static const char* value()
  {
    return "box_generator/DeleteBox";
  }

  static const char* value(const ::box_generator::DeleteBox&) { return value(); }
};


// service_traits::MD5Sum< ::box_generator::DeleteBoxRequest> should match
// service_traits::MD5Sum< ::box_generator::DeleteBox >
template<>
struct MD5Sum< ::box_generator::DeleteBoxRequest>
{
  static const char* value()
  {
    return MD5Sum< ::box_generator::DeleteBox >::value();
  }
  static const char* value(const ::box_generator::DeleteBoxRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::box_generator::DeleteBoxRequest> should match
// service_traits::DataType< ::box_generator::DeleteBox >
template<>
struct DataType< ::box_generator::DeleteBoxRequest>
{
  static const char* value()
  {
    return DataType< ::box_generator::DeleteBox >::value();
  }
  static const char* value(const ::box_generator::DeleteBoxRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::box_generator::DeleteBoxResponse> should match
// service_traits::MD5Sum< ::box_generator::DeleteBox >
template<>
struct MD5Sum< ::box_generator::DeleteBoxResponse>
{
  static const char* value()
  {
    return MD5Sum< ::box_generator::DeleteBox >::value();
  }
  static const char* value(const ::box_generator::DeleteBoxResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::box_generator::DeleteBoxResponse> should match
// service_traits::DataType< ::box_generator::DeleteBox >
template<>
struct DataType< ::box_generator::DeleteBoxResponse>
{
  static const char* value()
  {
    return DataType< ::box_generator::DeleteBox >::value();
  }
  static const char* value(const ::box_generator::DeleteBoxResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BOX_GENERATOR_MESSAGE_DELETEBOX_H
