// Generated by gencpp from file box_generator/DeleteBoxRequest.msg
// DO NOT EDIT!


#ifndef BOX_GENERATOR_MESSAGE_DELETEBOXREQUEST_H
#define BOX_GENERATOR_MESSAGE_DELETEBOXREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace box_generator
{
template <class ContainerAllocator>
struct DeleteBoxRequest_
{
  typedef DeleteBoxRequest_<ContainerAllocator> Type;

  DeleteBoxRequest_()
    : boxes_id()  {
    }
  DeleteBoxRequest_(const ContainerAllocator& _alloc)
    : boxes_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _boxes_id_type;
  _boxes_id_type boxes_id;





  typedef boost::shared_ptr< ::box_generator::DeleteBoxRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::box_generator::DeleteBoxRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DeleteBoxRequest_

typedef ::box_generator::DeleteBoxRequest_<std::allocator<void> > DeleteBoxRequest;

typedef boost::shared_ptr< ::box_generator::DeleteBoxRequest > DeleteBoxRequestPtr;
typedef boost::shared_ptr< ::box_generator::DeleteBoxRequest const> DeleteBoxRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::box_generator::DeleteBoxRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::box_generator::DeleteBoxRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::box_generator::DeleteBoxRequest_<ContainerAllocator1> & lhs, const ::box_generator::DeleteBoxRequest_<ContainerAllocator2> & rhs)
{
  return lhs.boxes_id == rhs.boxes_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::box_generator::DeleteBoxRequest_<ContainerAllocator1> & lhs, const ::box_generator::DeleteBoxRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace box_generator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::box_generator::DeleteBoxRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::box_generator::DeleteBoxRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::box_generator::DeleteBoxRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::box_generator::DeleteBoxRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::box_generator::DeleteBoxRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::box_generator::DeleteBoxRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::box_generator::DeleteBoxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7bb18cad593afae40bcd0fb4ccb9250b";
  }

  static const char* value(const ::box_generator::DeleteBoxRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7bb18cad593afae4ULL;
  static const uint64_t static_value2 = 0x0bcd0fb4ccb9250bULL;
};

template<class ContainerAllocator>
struct DataType< ::box_generator::DeleteBoxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "box_generator/DeleteBoxRequest";
  }

  static const char* value(const ::box_generator::DeleteBoxRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::box_generator::DeleteBoxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] boxes_id\n"
;
  }

  static const char* value(const ::box_generator::DeleteBoxRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::box_generator::DeleteBoxRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.boxes_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeleteBoxRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::box_generator::DeleteBoxRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::box_generator::DeleteBoxRequest_<ContainerAllocator>& v)
  {
    s << indent << "boxes_id[]" << std::endl;
    for (size_t i = 0; i < v.boxes_id.size(); ++i)
    {
      s << indent << "  boxes_id[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.boxes_id[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOX_GENERATOR_MESSAGE_DELETEBOXREQUEST_H
