// Generated by gencpp from file box_generator/MqttListener.msg
// DO NOT EDIT!


#ifndef BOX_GENERATOR_MESSAGE_MQTTLISTENER_H
#define BOX_GENERATOR_MESSAGE_MQTTLISTENER_H

#include <ros/service_traits.h>


#include <box_generator/MqttListenerRequest.h>
#include <box_generator/MqttListenerResponse.h>


namespace box_generator
{

struct MqttListener
{

typedef MqttListenerRequest Request;
typedef MqttListenerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MqttListener
} // namespace box_generator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::box_generator::MqttListener > {
  static const char* value()
  {
    return "eca67f62be2b35d15d597743c12e190f";
  }

  static const char* value(const ::box_generator::MqttListener&) { return value(); }
};

template<>
struct DataType< ::box_generator::MqttListener > {
  static const char* value()
  {
    return "box_generator/MqttListener";
  }

  static const char* value(const ::box_generator::MqttListener&) { return value(); }
};


// service_traits::MD5Sum< ::box_generator::MqttListenerRequest> should match
// service_traits::MD5Sum< ::box_generator::MqttListener >
template<>
struct MD5Sum< ::box_generator::MqttListenerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::box_generator::MqttListener >::value();
  }
  static const char* value(const ::box_generator::MqttListenerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::box_generator::MqttListenerRequest> should match
// service_traits::DataType< ::box_generator::MqttListener >
template<>
struct DataType< ::box_generator::MqttListenerRequest>
{
  static const char* value()
  {
    return DataType< ::box_generator::MqttListener >::value();
  }
  static const char* value(const ::box_generator::MqttListenerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::box_generator::MqttListenerResponse> should match
// service_traits::MD5Sum< ::box_generator::MqttListener >
template<>
struct MD5Sum< ::box_generator::MqttListenerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::box_generator::MqttListener >::value();
  }
  static const char* value(const ::box_generator::MqttListenerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::box_generator::MqttListenerResponse> should match
// service_traits::DataType< ::box_generator::MqttListener >
template<>
struct DataType< ::box_generator::MqttListenerResponse>
{
  static const char* value()
  {
    return DataType< ::box_generator::MqttListener >::value();
  }
  static const char* value(const ::box_generator::MqttListenerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BOX_GENERATOR_MESSAGE_MQTTLISTENER_H
