// Generated by gencpp from file box_generator/MqttListenerRequest.msg
// DO NOT EDIT!


#ifndef BOX_GENERATOR_MESSAGE_MQTTLISTENERREQUEST_H
#define BOX_GENERATOR_MESSAGE_MQTTLISTENERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace box_generator
{
template <class ContainerAllocator>
struct MqttListenerRequest_
{
  typedef MqttListenerRequest_<ContainerAllocator> Type;

  MqttListenerRequest_()
    {
    }
  MqttListenerRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::box_generator::MqttListenerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::box_generator::MqttListenerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MqttListenerRequest_

typedef ::box_generator::MqttListenerRequest_<std::allocator<void> > MqttListenerRequest;

typedef boost::shared_ptr< ::box_generator::MqttListenerRequest > MqttListenerRequestPtr;
typedef boost::shared_ptr< ::box_generator::MqttListenerRequest const> MqttListenerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::box_generator::MqttListenerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::box_generator::MqttListenerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace box_generator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::box_generator::MqttListenerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::box_generator::MqttListenerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::box_generator::MqttListenerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::box_generator::MqttListenerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::box_generator::MqttListenerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::box_generator::MqttListenerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::box_generator::MqttListenerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::box_generator::MqttListenerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::box_generator::MqttListenerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "box_generator/MqttListenerRequest";
  }

  static const char* value(const ::box_generator::MqttListenerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::box_generator::MqttListenerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::box_generator::MqttListenerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::box_generator::MqttListenerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MqttListenerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::box_generator::MqttListenerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::box_generator::MqttListenerRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // BOX_GENERATOR_MESSAGE_MQTTLISTENERREQUEST_H
