// Generated by gencpp from file box_generator/SetParam.msg
// DO NOT EDIT!


#ifndef BOX_GENERATOR_MESSAGE_SETPARAM_H
#define BOX_GENERATOR_MESSAGE_SETPARAM_H

#include <ros/service_traits.h>


#include <box_generator/SetParamRequest.h>
#include <box_generator/SetParamResponse.h>


namespace box_generator
{

struct SetParam
{

typedef SetParamRequest Request;
typedef SetParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetParam
} // namespace box_generator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::box_generator::SetParam > {
  static const char* value()
  {
    return "3e7c329fec6fea0b39dd75f575b3c45d";
  }

  static const char* value(const ::box_generator::SetParam&) { return value(); }
};

template<>
struct DataType< ::box_generator::SetParam > {
  static const char* value()
  {
    return "box_generator/SetParam";
  }

  static const char* value(const ::box_generator::SetParam&) { return value(); }
};


// service_traits::MD5Sum< ::box_generator::SetParamRequest> should match
// service_traits::MD5Sum< ::box_generator::SetParam >
template<>
struct MD5Sum< ::box_generator::SetParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::box_generator::SetParam >::value();
  }
  static const char* value(const ::box_generator::SetParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::box_generator::SetParamRequest> should match
// service_traits::DataType< ::box_generator::SetParam >
template<>
struct DataType< ::box_generator::SetParamRequest>
{
  static const char* value()
  {
    return DataType< ::box_generator::SetParam >::value();
  }
  static const char* value(const ::box_generator::SetParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::box_generator::SetParamResponse> should match
// service_traits::MD5Sum< ::box_generator::SetParam >
template<>
struct MD5Sum< ::box_generator::SetParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::box_generator::SetParam >::value();
  }
  static const char* value(const ::box_generator::SetParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::box_generator::SetParamResponse> should match
// service_traits::DataType< ::box_generator::SetParam >
template<>
struct DataType< ::box_generator::SetParamResponse>
{
  static const char* value()
  {
    return DataType< ::box_generator::SetParam >::value();
  }
  static const char* value(const ::box_generator::SetParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BOX_GENERATOR_MESSAGE_SETPARAM_H
