// Generated by gencpp from file box_generator/SpawnBoxRequest.msg
// DO NOT EDIT!


#ifndef BOX_GENERATOR_MESSAGE_SPAWNBOXREQUEST_H
#define BOX_GENERATOR_MESSAGE_SPAWNBOXREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace box_generator
{
template <class ContainerAllocator>
struct SpawnBoxRequest_
{
  typedef SpawnBoxRequest_<ContainerAllocator> Type;

  SpawnBoxRequest_()
    : boxes_id()
    , mass(0.0)
    , length(0.0)
    , width(0.0)
    , height(0.0)  {
    }
  SpawnBoxRequest_(const ContainerAllocator& _alloc)
    : boxes_id(_alloc)
    , mass(0.0)
    , length(0.0)
    , width(0.0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _boxes_id_type;
  _boxes_id_type boxes_id;

   typedef float _mass_type;
  _mass_type mass;

   typedef float _length_type;
  _length_type length;

   typedef float _width_type;
  _width_type width;

   typedef float _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::box_generator::SpawnBoxRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::box_generator::SpawnBoxRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SpawnBoxRequest_

typedef ::box_generator::SpawnBoxRequest_<std::allocator<void> > SpawnBoxRequest;

typedef boost::shared_ptr< ::box_generator::SpawnBoxRequest > SpawnBoxRequestPtr;
typedef boost::shared_ptr< ::box_generator::SpawnBoxRequest const> SpawnBoxRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::box_generator::SpawnBoxRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::box_generator::SpawnBoxRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::box_generator::SpawnBoxRequest_<ContainerAllocator1> & lhs, const ::box_generator::SpawnBoxRequest_<ContainerAllocator2> & rhs)
{
  return lhs.boxes_id == rhs.boxes_id &&
    lhs.mass == rhs.mass &&
    lhs.length == rhs.length &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::box_generator::SpawnBoxRequest_<ContainerAllocator1> & lhs, const ::box_generator::SpawnBoxRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace box_generator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::box_generator::SpawnBoxRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::box_generator::SpawnBoxRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::box_generator::SpawnBoxRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::box_generator::SpawnBoxRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::box_generator::SpawnBoxRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::box_generator::SpawnBoxRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::box_generator::SpawnBoxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5447832cd5e8c8500cebb7f2a031fce0";
  }

  static const char* value(const ::box_generator::SpawnBoxRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5447832cd5e8c850ULL;
  static const uint64_t static_value2 = 0x0cebb7f2a031fce0ULL;
};

template<class ContainerAllocator>
struct DataType< ::box_generator::SpawnBoxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "box_generator/SpawnBoxRequest";
  }

  static const char* value(const ::box_generator::SpawnBoxRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::box_generator::SpawnBoxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] boxes_id\n"
"float32 mass\n"
"float32 length\n"
"float32 width\n"
"float32 height\n"
;
  }

  static const char* value(const ::box_generator::SpawnBoxRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::box_generator::SpawnBoxRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.boxes_id);
      stream.next(m.mass);
      stream.next(m.length);
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpawnBoxRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::box_generator::SpawnBoxRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::box_generator::SpawnBoxRequest_<ContainerAllocator>& v)
  {
    s << indent << "boxes_id[]" << std::endl;
    for (size_t i = 0; i < v.boxes_id.size(); ++i)
    {
      s << indent << "  boxes_id[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.boxes_id[i]);
    }
    s << indent << "mass: ";
    Printer<float>::stream(s, indent + "  ", v.mass);
    s << indent << "length: ";
    Printer<float>::stream(s, indent + "  ", v.length);
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOX_GENERATOR_MESSAGE_SPAWNBOXREQUEST_H
