// Generated by gencpp from file box_generator/SpawnBox.msg
// DO NOT EDIT!


#ifndef BOX_GENERATOR_MESSAGE_SPAWNBOX_H
#define BOX_GENERATOR_MESSAGE_SPAWNBOX_H

#include <ros/service_traits.h>


#include <box_generator/SpawnBoxRequest.h>
#include <box_generator/SpawnBoxResponse.h>


namespace box_generator
{

struct SpawnBox
{

typedef SpawnBoxRequest Request;
typedef SpawnBoxResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpawnBox
} // namespace box_generator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::box_generator::SpawnBox > {
  static const char* value()
  {
    return "48f94fb5a1b1f9bff04b2ea497ff928c";
  }

  static const char* value(const ::box_generator::SpawnBox&) { return value(); }
};

template<>
struct DataType< ::box_generator::SpawnBox > {
  static const char* value()
  {
    return "box_generator/SpawnBox";
  }

  static const char* value(const ::box_generator::SpawnBox&) { return value(); }
};


// service_traits::MD5Sum< ::box_generator::SpawnBoxRequest> should match
// service_traits::MD5Sum< ::box_generator::SpawnBox >
template<>
struct MD5Sum< ::box_generator::SpawnBoxRequest>
{
  static const char* value()
  {
    return MD5Sum< ::box_generator::SpawnBox >::value();
  }
  static const char* value(const ::box_generator::SpawnBoxRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::box_generator::SpawnBoxRequest> should match
// service_traits::DataType< ::box_generator::SpawnBox >
template<>
struct DataType< ::box_generator::SpawnBoxRequest>
{
  static const char* value()
  {
    return DataType< ::box_generator::SpawnBox >::value();
  }
  static const char* value(const ::box_generator::SpawnBoxRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::box_generator::SpawnBoxResponse> should match
// service_traits::MD5Sum< ::box_generator::SpawnBox >
template<>
struct MD5Sum< ::box_generator::SpawnBoxResponse>
{
  static const char* value()
  {
    return MD5Sum< ::box_generator::SpawnBox >::value();
  }
  static const char* value(const ::box_generator::SpawnBoxResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::box_generator::SpawnBoxResponse> should match
// service_traits::DataType< ::box_generator::SpawnBox >
template<>
struct DataType< ::box_generator::SpawnBoxResponse>
{
  static const char* value()
  {
    return DataType< ::box_generator::SpawnBox >::value();
  }
  static const char* value(const ::box_generator::SpawnBoxResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BOX_GENERATOR_MESSAGE_SPAWNBOX_H
