// Generated by gencpp from file box_generator/WaypointSenderResponse.msg
// DO NOT EDIT!


#ifndef BOX_GENERATOR_MESSAGE_WAYPOINTSENDERRESPONSE_H
#define BOX_GENERATOR_MESSAGE_WAYPOINTSENDERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace box_generator
{
template <class ContainerAllocator>
struct WaypointSenderResponse_
{
  typedef WaypointSenderResponse_<ContainerAllocator> Type;

  WaypointSenderResponse_()
    : success(false)
    , message()  {
    }
  WaypointSenderResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::box_generator::WaypointSenderResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::box_generator::WaypointSenderResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointSenderResponse_

typedef ::box_generator::WaypointSenderResponse_<std::allocator<void> > WaypointSenderResponse;

typedef boost::shared_ptr< ::box_generator::WaypointSenderResponse > WaypointSenderResponsePtr;
typedef boost::shared_ptr< ::box_generator::WaypointSenderResponse const> WaypointSenderResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::box_generator::WaypointSenderResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::box_generator::WaypointSenderResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::box_generator::WaypointSenderResponse_<ContainerAllocator1> & lhs, const ::box_generator::WaypointSenderResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::box_generator::WaypointSenderResponse_<ContainerAllocator1> & lhs, const ::box_generator::WaypointSenderResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace box_generator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::box_generator::WaypointSenderResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::box_generator::WaypointSenderResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::box_generator::WaypointSenderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::box_generator::WaypointSenderResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::box_generator::WaypointSenderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::box_generator::WaypointSenderResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::box_generator::WaypointSenderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::box_generator::WaypointSenderResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::box_generator::WaypointSenderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "box_generator/WaypointSenderResponse";
  }

  static const char* value(const ::box_generator::WaypointSenderResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::box_generator::WaypointSenderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response\n"
"bool success\n"
"string message\n"
;
  }

  static const char* value(const ::box_generator::WaypointSenderResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::box_generator::WaypointSenderResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointSenderResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::box_generator::WaypointSenderResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::box_generator::WaypointSenderResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOX_GENERATOR_MESSAGE_WAYPOINTSENDERRESPONSE_H
