// Generated by gencpp from file box_generator/WaypointSenderRequest.msg
// DO NOT EDIT!


#ifndef BOX_GENERATOR_MESSAGE_WAYPOINTSENDERREQUEST_H
#define BOX_GENERATOR_MESSAGE_WAYPOINTSENDERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace box_generator
{
template <class ContainerAllocator>
struct WaypointSenderRequest_
{
  typedef WaypointSenderRequest_<ContainerAllocator> Type;

  WaypointSenderRequest_()
    : position_x(0.0)
    , position_y(0.0)
    , position_z(0.0)
    , orientation_x(0.0)
    , orientation_y(0.0)
    , orientation_z(0.0)
    , orientation_w(0.0)  {
    }
  WaypointSenderRequest_(const ContainerAllocator& _alloc)
    : position_x(0.0)
    , position_y(0.0)
    , position_z(0.0)
    , orientation_x(0.0)
    , orientation_y(0.0)
    , orientation_z(0.0)
    , orientation_w(0.0)  {
  (void)_alloc;
    }



   typedef double _position_x_type;
  _position_x_type position_x;

   typedef double _position_y_type;
  _position_y_type position_y;

   typedef double _position_z_type;
  _position_z_type position_z;

   typedef double _orientation_x_type;
  _orientation_x_type orientation_x;

   typedef double _orientation_y_type;
  _orientation_y_type orientation_y;

   typedef double _orientation_z_type;
  _orientation_z_type orientation_z;

   typedef double _orientation_w_type;
  _orientation_w_type orientation_w;





  typedef boost::shared_ptr< ::box_generator::WaypointSenderRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::box_generator::WaypointSenderRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointSenderRequest_

typedef ::box_generator::WaypointSenderRequest_<std::allocator<void> > WaypointSenderRequest;

typedef boost::shared_ptr< ::box_generator::WaypointSenderRequest > WaypointSenderRequestPtr;
typedef boost::shared_ptr< ::box_generator::WaypointSenderRequest const> WaypointSenderRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::box_generator::WaypointSenderRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::box_generator::WaypointSenderRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::box_generator::WaypointSenderRequest_<ContainerAllocator1> & lhs, const ::box_generator::WaypointSenderRequest_<ContainerAllocator2> & rhs)
{
  return lhs.position_x == rhs.position_x &&
    lhs.position_y == rhs.position_y &&
    lhs.position_z == rhs.position_z &&
    lhs.orientation_x == rhs.orientation_x &&
    lhs.orientation_y == rhs.orientation_y &&
    lhs.orientation_z == rhs.orientation_z &&
    lhs.orientation_w == rhs.orientation_w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::box_generator::WaypointSenderRequest_<ContainerAllocator1> & lhs, const ::box_generator::WaypointSenderRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace box_generator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::box_generator::WaypointSenderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::box_generator::WaypointSenderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::box_generator::WaypointSenderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::box_generator::WaypointSenderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::box_generator::WaypointSenderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::box_generator::WaypointSenderRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::box_generator::WaypointSenderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e901576f4a49a1550b5eb904609813b";
  }

  static const char* value(const ::box_generator::WaypointSenderRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e901576f4a49a15ULL;
  static const uint64_t static_value2 = 0x50b5eb904609813bULL;
};

template<class ContainerAllocator>
struct DataType< ::box_generator::WaypointSenderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "box_generator/WaypointSenderRequest";
  }

  static const char* value(const ::box_generator::WaypointSenderRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::box_generator::WaypointSenderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"float64 position_x\n"
"float64 position_y\n"
"float64 position_z\n"
"float64 orientation_x\n"
"float64 orientation_y\n"
"float64 orientation_z\n"
"float64 orientation_w\n"
"\n"
;
  }

  static const char* value(const ::box_generator::WaypointSenderRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::box_generator::WaypointSenderRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position_x);
      stream.next(m.position_y);
      stream.next(m.position_z);
      stream.next(m.orientation_x);
      stream.next(m.orientation_y);
      stream.next(m.orientation_z);
      stream.next(m.orientation_w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointSenderRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::box_generator::WaypointSenderRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::box_generator::WaypointSenderRequest_<ContainerAllocator>& v)
  {
    s << indent << "position_x: ";
    Printer<double>::stream(s, indent + "  ", v.position_x);
    s << indent << "position_y: ";
    Printer<double>::stream(s, indent + "  ", v.position_y);
    s << indent << "position_z: ";
    Printer<double>::stream(s, indent + "  ", v.position_z);
    s << indent << "orientation_x: ";
    Printer<double>::stream(s, indent + "  ", v.orientation_x);
    s << indent << "orientation_y: ";
    Printer<double>::stream(s, indent + "  ", v.orientation_y);
    s << indent << "orientation_z: ";
    Printer<double>::stream(s, indent + "  ", v.orientation_z);
    s << indent << "orientation_w: ";
    Printer<double>::stream(s, indent + "  ", v.orientation_w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOX_GENERATOR_MESSAGE_WAYPOINTSENDERREQUEST_H
