// Generated by gencpp from file box_generator/WaypointSender.msg
// DO NOT EDIT!


#ifndef BOX_GENERATOR_MESSAGE_WAYPOINTSENDER_H
#define BOX_GENERATOR_MESSAGE_WAYPOINTSENDER_H

#include <ros/service_traits.h>


#include <box_generator/WaypointSenderRequest.h>
#include <box_generator/WaypointSenderResponse.h>


namespace box_generator
{

struct WaypointSender
{

typedef WaypointSenderRequest Request;
typedef WaypointSenderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WaypointSender
} // namespace box_generator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::box_generator::WaypointSender > {
  static const char* value()
  {
    return "551b10962421931d26e170ffc7184147";
  }

  static const char* value(const ::box_generator::WaypointSender&) { return value(); }
};

template<>
struct DataType< ::box_generator::WaypointSender > {
  static const char* value()
  {
    return "box_generator/WaypointSender";
  }

  static const char* value(const ::box_generator::WaypointSender&) { return value(); }
};


// service_traits::MD5Sum< ::box_generator::WaypointSenderRequest> should match
// service_traits::MD5Sum< ::box_generator::WaypointSender >
template<>
struct MD5Sum< ::box_generator::WaypointSenderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::box_generator::WaypointSender >::value();
  }
  static const char* value(const ::box_generator::WaypointSenderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::box_generator::WaypointSenderRequest> should match
// service_traits::DataType< ::box_generator::WaypointSender >
template<>
struct DataType< ::box_generator::WaypointSenderRequest>
{
  static const char* value()
  {
    return DataType< ::box_generator::WaypointSender >::value();
  }
  static const char* value(const ::box_generator::WaypointSenderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::box_generator::WaypointSenderResponse> should match
// service_traits::MD5Sum< ::box_generator::WaypointSender >
template<>
struct MD5Sum< ::box_generator::WaypointSenderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::box_generator::WaypointSender >::value();
  }
  static const char* value(const ::box_generator::WaypointSenderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::box_generator::WaypointSenderResponse> should match
// service_traits::DataType< ::box_generator::WaypointSender >
template<>
struct DataType< ::box_generator::WaypointSenderResponse>
{
  static const char* value()
  {
    return DataType< ::box_generator::WaypointSender >::value();
  }
  static const char* value(const ::box_generator::WaypointSenderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BOX_GENERATOR_MESSAGE_WAYPOINTSENDER_H
