(cl:defpackage box_generator-srv
  (:use )
  (:export
   "DELETEBOX"
   "<DELETEBOX-REQUEST>"
   "DELETEBOX-REQUEST"
   "<DELETEBOX-RESPONSE>"
   "DELETEBOX-RESPONSE"
   "SPAWNBOX"
   "<SPAWNBOX-REQUEST>"
   "SPAWNBOX-REQUEST"
   "<SPAWNBOX-RESPONSE>"
   "SPAWNBOX-RESPONSE"
  ))

